pipeline {
   agent {
      docker {
         image 'maven:3-alpine'
         args '-v /root/.m2:/root/.m2'
      }
   }
   stages {
      stage('Maven Build') {
         steps {
            echo'Begin Maven Build'
            sh 'mvn clean install'
         }
         post {
            success {
               echo 'Build Successful!'
               echo 'Archiving Artifacts'
               archiveArtifacts artifacts: '**/*.jar'
            }
            failure {
               echo 'Build Failed!'
            }
         }
      }
   }
}